### ISSUE TITLE
Enhance comment of dkzg.Commit()

### ISSUE THREAD

**Issue by SadPencil** [dreamATD/pianist-gnark-crypto#2]
Hi.

The comment of function `dkzg.Commit()` seems to be a little bit confusing to me:
- Lagrange polynomial (same thing in your paper, Sec. 2.1 Notations) could either mean one of these Lagrange basis polynomials or the final polynomial constructed from their linear combination. I spent some time to figure it which one is the correct meaning. Personally, I think it's better to explicitly call them Lagrange basis polynomials in code comments and the paper.
- `f_{i, j} * U^{L_i(\tau[0])*\tau[1]^j}` seems to be incorrect because in your comments and your paper, the elliptic curve operations are defined in multiplicative group (`(U^{L_i(\tau[0])*\tau[1]^j})^f_{i, j}` ) instead of additive group (`f_{i, j} * U^{L_i(\tau[0])*\tau[1]^j}`).
- In your paper (Protocol 2), the polynomial that each party holds is in Lagrange interpolation form `f_i(X) = \sum_{j=0}^{T-1} f_{i, j} * L_j(X)` (T = N), while in your codes it is denoted as `f_i(y) = \sum_{j=0}^{N-1} f_{i, j} * y^j`. So it's better to write the definition of `f_i(y)` here to make the intended meaning clear.

Below are my changes:

```diff
diff --git a/ecc/bn254/fr/dkzg/dkzg.go b/ecc/bn254/fr/dkzg/dkzg.go
index 8a8d99dd..cd894d76 100644
--- a/ecc/bn254/fr/dkzg/dkzg.go
+++ b/ecc/bn254/fr/dkzg/dkzg.go
@@ -120,9 +120,9 @@ func NewSRS(size uint64, tau []*big.Int, domainGenY *fr.Element) (*SRS, error) {

 /*
 The distributed commit algorithm computes the following:
- 1. Each node has a polynomial f_i(y).
- 2. The commit algorithm commits to: F(x, y) = \sum_{i=0}^{M-1} f_i(y) * L_i(x), where L_i(x) is the Lagrange polynomial of i.
- 3. The commitment is g^{F(\tau[0], \tau[1])} = \Pi_{i=0}^{M-1} g^{f_i(\tau[1]) * L_i(\tau[0])} = \Pi_{i=0}^{M-1}\Pi_{j=0}^{N-1}f_{i, j} * U^{L_i(\tau[0])*\tau[1]^j}.
+ 1. Each node has a polynomial f_i(y) = \sum_{j=0}^{N-1} f_{i, j} * y^j.
+ 2. The commit algorithm commits to: F(x, y) = \sum_{i=0}^{M-1} f_i(y) * L_i(x), where L_i(x) is the Lagrange basis polynomial of i.
+ 3. The commitment is g^{F(\tau[0], \tau[1])} = \Pi_{i=0}^{M-1} g^{f_i(\tau[1]) * L_i(\tau[0])} = \Pi_{i=0}^{M-1}\Pi_{j=0}^{N-1} g^{f_{i, j} * \tau{1}^j * L_i(\tau[0])} = \Pi_{i=0}^{M-1}\Pi_{j=0}^{N-1} (g^{L_i(\tau[0])*\tau[1]^j}) ^ f_{i, j} = \Pi_{i=0}^{M-1}\Pi_{j=0}^{N-1} U ^ f_{i, j}, where U = srs.G1[j].
 */
 func Commit(p []fr.Element, srs *SRS, nbTasks ...int) (Digest, error) {
        // Each compute node computes the commitment of its own polynomial
```

**Comment by dreamATD** [comment]
Thank you for pointing it out!
